language: node_js
node_js:
  - "7"
  - "node"
env:
  - NODE_ENV=ci
cache:
  directories:
  - node_modules
install:
  - lerna bootstrap
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - lerna run --scope treact build:vendor
  - lerna run --scope treact build
  - lerna run --scope treact test
